spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill-redis
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 14
    host: 192.168.82.13
    password:
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 100
        max-wait: 100000ms
    timeout: 1000