spring:
  redis:
    database: 14
    host: 192.168.82.13
    password:
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 100
        max-wait: 100000ms
    timeout: 1000